-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgukO2jhNSwxAISanH
fSfmYeIBV5vUt3XgOcy535n5OsegCgYIKoZIzj0DAQehRANCAATLvnRxMxTvdSAs
C5KfzQ7ycwaWNeBzvh8XE2qPVIENkXkHNlUeW9f9W3r8VbMFCYKLPSJnlZUVWTag
Mk10EFfW
-----END PRIVATE KEY-----